name: After Run Actions
description: 'After Run Steps: Copy Data, Download Parquet, Generate Token, Commit Data'
inputs:
    COMMAND:
        description: 'COMMAND'
        required: true
    APP_ID:
        description: 'APP_ID'
        required: true
    PRIVATE_KEY:
        description: 'PRIVATE_KEY'
        required: true
runs:
    using: composite
    steps:
    - name: Copy data files
      shell: bash
      run: |
        set -Eeuo pipefail

        copy() {
          local SRC="$1"
          local DEST="$2"
          echo "• $SRC → $DEST"
          if [[ -f "$SRC" ]]; then
            mkdir -p "$(dirname "$DEST")"
            cp "$SRC" "$DEST"
            echo "  ✅ Copy successful: $DEST"
          else
            echo "  ❌ Source file missing: $SRC"
            # exit 1   # remove or change to 'return 0' if you want to skip missing files
          fi
        }

        copy "./src/June.Data/bin/Release/net9.0/Data/data.json" "./src/myenergy/wwwroot/Data/data.json"
        copy "./src/June.Data/bin/Release/net9.0/Data/consolidated.json" "./src/myenergy/wwwroot/Data/consolidated.json"
        copy "./src/June.Data/bin/Release/net9.0/Data/data.json" "./src/June.Data/Data/data.json"

    - name: Download ODS Parquet file from Elia
      shell: bash
      run: |
        set -Eeuo pipefail
        
        PARQUET_URL="https://opendata.elia.be/api/explore/v2.1/catalog/datasets/ods134/exports/parquet?lang=en&timezone=Europe%2FBrussels"
        PARQUET_DEST="./src/myenergy/wwwroot/Data/ods134.parquet"
        
        echo "📥 Downloading ODS Parquet file from Elia..."
        echo "  URL: $PARQUET_URL"
        echo "  Destination: $PARQUET_DEST"
        
        # Create directory if it doesn't exist
        mkdir -p "$(dirname "$PARQUET_DEST")"
        
        # Download with curl (shows progress)
        if curl -fSL --progress-bar -o "$PARQUET_DEST" "$PARQUET_URL"; then
          FILE_SIZE=$(stat -c%s "$PARQUET_DEST" 2>/dev/null || stat -f%z "$PARQUET_DEST" 2>/dev/null || echo "unknown")
          echo "  ✅ Download successful: $PARQUET_DEST"
          echo "  📊 File size: $FILE_SIZE bytes"
        else
          echo "  ❌ Download failed"
          exit 1
        fi

    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.PRIVATE_KEY }}
        
    - name: Commit Data Files
      shell: bash
      run: |
        git config --global user.name 'Sujith Quintelier'
        git config --global user.email 'sujith.quintelier@gmail.com'

        # Function to commit a file if changed
        commit_if_changed() {
          local FILE_PATH="$1"
          local FILE_DESC="$2"
          
          if git diff --quiet HEAD -- "$FILE_PATH" ; then
            echo "✓ No changes to $FILE_DESC"
          else
            echo "📝 Committing changes to $FILE_DESC..."
            git add "$FILE_PATH"
            git commit -m "📊 Update $FILE_DESC for ${{ inputs.COMMAND }}"
            git push origin main
            echo "  ✅ Pushed $FILE_DESC"
          fi
        }

        # Commit data.json
        commit_if_changed "./src/myenergy/wwwroot/Data/data.json" "data file"
        
        # Commit consolidated.json
        commit_if_changed "./src/myenergy/wwwroot/Data/consolidated.json" "consolidated file"
        
        # Commit ODS Parquet file
        commit_if_changed "./src/myenergy/wwwroot/Data/ods134.parquet" "ODS Parquet file"
        
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
