name: After Run Actions
description: 'After Run Steps: Copy Data, Generate Token, Commit Data'
inputs:
    COMMAND:
        description: 'COMMAND'
        required: true
    APP_ID:
        description: 'APP_ID'
        required: true
    PRIVATE_KEY:
        description: 'PRIVATE_KEY'
        required: true
runs:
    using: composite
    steps:
    - name: Copy data file
      shell: bash
      run: |
          cp ./src/June.Data/bin/Release/net8.0/Data/data.json ./src/myenergy/wwwroot/Data/data.json
          cp ./src/June.Data/bin/Release/net8.0/Data/data.json ./src/June.Data/Data/data.json
            if [ $? -eq 0 ]; then
                echo "Copy successful."
            else
                echo "Copy failed."
            fi
    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.PRIVATE_KEY }}
    - name: Commit Data File
      shell: bash
      run: |
        git config --global user.name 'Sujith Quintelier'
        git config --global user.email 'sujith.quintelier@gmail.com'

        git diff HEAD -- "./src/myenergy/wwwroot/Data/data.json"

        if git diff --quiet HEAD -- "./src/myenergy/wwwroot/Data/data.json" ; then
            echo "No changes to the output on this push."
        else
            git add ./src/myenergy/wwwroot/Data/data.json
            git commit -m "📊 Add update data file for ${{ inputs.COMMAND }}."
            git push origin main
        fi

        git diff HEAD -- "./src/June.Data/Data/data.json"

        if git diff --quiet HEAD -- "./src/June.Data/Data/data.json" ; then
            echo "No changes to the output on this push."
        else
            git add ./src/June.Data/Data/data.json
            git commit -m "📊 Add update data file for ${{ inputs.COMMAND }}."
            git push origin main
        fi
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}