name: After Run Actions
description: 'After Run Steps: Copy Data, Generate Token, Commit Data'
inputs:
    COMMAND:
        description: 'COMMAND'
        required: true
    APP_ID:
        description: 'APP_ID'
        required: true
    PRIVATE_KEY:
        description: 'PRIVATE_KEY'
        required: true
runs:
    using: composite
    steps:
    - name: Copy data files
      shell: bash
      run: |
        set -Eeuo pipefail

        copy() {
          local SRC="$1"
          local DEST="$2"
          echo "• $SRC → $DEST"
          if [[ -f "$SRC" ]]; then
            mkdir -p "$(dirname "$DEST")"
            cp "$SRC" "$DEST"
            echo "  ✅ Copy successful: $DEST"
          else
            echo "  ❌ Source file missing: $SRC"
            # exit 1   # remove or change to 'return 0' if you want to skip missing files
          fi
        }

        copy "./src/June.Data/bin/Release/net9.0/Data/data.json" "./src/myenergy/wwwroot/Data/data.json"
        copy "./src/June.Data/bin/Release/net9.0/Data/consolidated.json" "./src/myenergy/wwwroot/Data/consolidated.json"
        copy "./src/June.Data/bin/Release/net9.0/Data/data.json" "./src/June.Data/Data/data.json"

    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.PRIVATE_KEY }}
    - name: Commit Data File
      shell: bash
      run: |
        git config --global user.name 'Sujith Quintelier'
        git config --global user.email 'sujith.quintelier@gmail.com'

        # git diff HEAD -- "./src/myenergy/wwwroot/Data/data.json"

        if git diff --quiet HEAD -- "./src/myenergy/wwwroot/Data/data.json" ; then
            echo "No changes to the output on this push."
        else
            git add ./src/myenergy/wwwroot/Data/data.json
            git commit -m "📊 Add update data file for ${{ inputs.COMMAND }}."
            git push origin main
        fi

        if git diff --quiet HEAD -- "./src/myenergy/wwwroot/Data/consolidated.json" ; then
            echo "No changes to the output on this push."
        else
            git add ./src/myenergy/wwwroot/Data/consolidated.json
            git commit -m "📊 Add update consolidated file for ${{ inputs.COMMAND }}."
            git push origin main
        fi
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}