name: Before Run Actions
description: ''
inputs:
    DOTNET-VERSION:
        description: 'The version of the .NET Core SDK to use. Supported values are 9.0.x. The latest patch version of each minor version is used if the patch version is omitted.'
        required: true
        default: '9.0.x'
runs:
    using: composite
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    # sets up .NET Core SDK ${{ inputs.dotnet-version }}
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.DOTNET-VERSION }}
    # Copy data file
    - name: Copy data file
      shell: bash
      run: |
        cp ./src/myenergy/wwwroot/Data/data.json ./src/June.Data/Data/data.json
        if [ $? -eq 0 ]; then
            echo "Copy successful."
        else
            echo "Copy failed."
        fi
        if [ -f ./src/myenergy/wwwroot/Data/consolidated.json ]; then
            cp ./src/myenergy/wwwroot/Data/consolidated.json ./src/June.Data/Data/consolidated.json
            if [ $? -eq 0 ]; then
                echo "Copy successful."
            else
                echo "Copy failed."
            fi
        else
            echo "consolidated.json not found in source, skipping copy."
        fi
    # Build Data
    - name: Build Data
      shell: bash
      run: dotnet build src/June.Data -c Release